import type { GlobalThemeOverrides } from 'naive-ui'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#26A69A',
    primaryColorHover: '#2BB5AA',
    primaryColorPressed: '#1F8F85',
    primaryColorSuppl: '#E0F5F3',
    errorColor: '#dc2626',
    errorColorHover: '#ef4444',
    errorColorPressed: '#b91c1c',
    errorColorSuppl: '#fef2f2',
    warningColor: '#f59e0b',
    warningColorHover: '#fbbf24',
    warningColorPressed: '#d97706',
    warningColorSuppl: '#fffbeb',
    successColor: '#16a34a',
    successColorHover: '#22c55e',
    successColorPressed: '#15803d',
    successColorSuppl: '#f0fdf4',
    infoColor: '#0284c7',
    infoColorHover: '#0ea5e9',
    infoColorPressed: '#0369a1',
    infoColorSuppl: '#e0f2fe',
    bodyColor: '#f0f4f8',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    inputColor: '#ffffff',
    actionColor: '#f8fafc',
    borderColor: '#e2e8f0',
    dividerColor: '#e2e8f0',
    hoverColor: '#f1f5f9',
    textColor1: '#1e293b',
    textColor2: '#475569',
    textColor3: '#94a3b8',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    fontFamily: '"Noto Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif',
    fontSize: '14px',
    fontSizeMini: '11px',
    fontSizeTiny: '12px',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    fontSizeLarge: '15px',
    fontSizeHuge: '16px',
    heightMini: '24px',
    heightTiny: '28px',
    heightSmall: '32px',
    heightMedium: '36px',
    heightLarge: '40px',
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusSmall: '6px',
    heightMedium: '36px',
    heightSmall: '32px',
    fontSizeMedium: '14px',
    fontWeight: '500',
  },
  Card: {
    borderRadius: '12px',
    paddingMedium: '16px 20px',
    titleFontSizeMedium: '15px',
    titleFontWeight: '600',
  },
  DataTable: {
    borderRadius: '8px',
    thColor: '#f8fafc',
    thFontWeight: '600',
    tdColor: '#ffffff',
    tdColorHover: '#f8fafc',
    borderColor: '#e2e8f0',
  },
  Input: {
    borderRadius: '8px',
    heightMedium: '36px',
    color: '#ffffff',
    colorFocus: '#ffffff',
    borderHover: '#2BB5AA',
    borderFocus: '#26A69A',
  },
  Select: {
    peers: {
      InternalSelection: {
        borderRadius: '8px',
        heightMedium: '36px',
      },
    },
  },
  Tag: {
    borderRadius: '6px',
    fontSizeMedium: '12px',
    heightMedium: '24px',
    padding: '0 8px',
  },
  Tabs: {
    tabBorderRadius: '8px',
    tabFontWeightActive: '600',
    tabGapSmallCard: '4px',
    tabPaddingSmallCard: '6px 12px',
  },
  Modal: {
    borderRadius: '12px',
    padding: '20px',
  },
  Form: {
    labelFontSizeTopMedium: '13px',
    feedbackFontSizeMedium: '12px',
    labelPaddingVertical: '0 0 6px 0',
  },
  Alert: {
    borderRadius: '8px',
  },
  Progress: {
    borderRadius: '4px',
  },
  Message: {
    borderRadius: '8px',
  },
}
